// Mock data for initial development
// This mimics the structure we'll get from the API

export const mockHikes = [
  {
    id: 1,
    number: 1,
    name: "JAMES PEAK",
    description: "James Peak offers stunning alpine scenery and glacial goodness. Start on St. Marys Glacier, traverse an alpine meadow, and then ascend an aesthetic dome to the top.",
    round_trip_miles: 7.28,
    hiking_time_min: 4.5,
    hiking_time_max: 6,
    difficulty_rating: 4,
    difficulty_label: "4/10",
    class_numeric: 2,
    class_text: "2",
    start_elevation: 10300,
    total_elevation_gain: 2950,
    terrain: "Year-round glacier, alpine plains, rocky slopes on the descent ridge",
    crowd_level_numeric: 4,
    crowd_level_text: "Moderate on the peak; high on the glacier",
    is_overnight: false,
    gear_advisor: "Crampons and ice ax in early spring",
    all_peaks: "James Peak (13,294')",
    highest_peak_elevation: 13294,
    peak_count: 1
  },
  {
    id: 2,
    number: 2,
    name: "NAVAJO PEAK",
    description: "A trip to the glacial basin below Navajo leads you to the base of Airplane Gully, where ghosts of the past await. A thrilling scramble is the grand finale to Navajo's airy summit.",
    round_trip_miles: 8.9,
    hiking_time_min: 6.5,
    hiking_time_max: 8,
    difficulty_rating: 8,
    difficulty_label: "8/10",
    class_numeric: 3,
    class_text: "3",
    start_elevation: 10500,
    total_elevation_gain: 2825,
    terrain: "Steep, loose gully and airy but solid scrambling on summit block",
    crowd_level_numeric: 2,
    crowd_level_text: "Low",
    is_overnight: false,
    gear_advisor: "Gaiters, stiff boots, ice ax in spring, helmet, and GPS",
    all_peaks: "Navajo Peak (13,409')",
    highest_peak_elevation: 13409,
    peak_count: 1
  },
  {
    id: 54,
    number: 54,
    name: "MOUNT FLORA",
    description: "Mount Flora is a pleasant hill walk that offers incredible views for not a lot of work, relatively speaking. Wander rolling ridges that are home to fields of wildflowers in the early summer and meadows of crimson grass in the autumn.",
    round_trip_miles: 6.4,
    hiking_time_min: 4,
    hiking_time_max: 5,
    difficulty_rating: 2,
    difficulty_label: "2/10",
    class_numeric: 1,
    class_text: "1",
    start_elevation: 11306,
    total_elevation_gain: 1830,
    terrain: "Class 1 trails along rolling ridges",
    crowd_level_numeric: 4,
    crowd_level_text: "Medium",
    is_overnight: false,
    gear_advisor: "Normal gear",
    all_peaks: "Mount Flora (13,132')",
    highest_peak_elevation: 13132,
    peak_count: 1
  },
  {
    id: 50,
    number: 50,
    name: "MOUNT ELBERT",
    description: "Colorado's highest peak is a straightforward climb that rewards hikers with incredible views. The standard route is a well-maintained trail that gains significant elevation.",
    round_trip_miles: 9.5,
    hiking_time_min: 6,
    hiking_time_max: 8,
    difficulty_rating: 5,
    difficulty_label: "5/10",
    class_numeric: 1,
    class_text: "1",
    start_elevation: 10040,
    total_elevation_gain: 4700,
    terrain: "Well-maintained trail with steady elevation gain",
    crowd_level_numeric: 5,
    crowd_level_text: "High",
    is_overnight: false,
    gear_advisor: "Normal gear, start early to avoid afternoon thunderstorms",
    all_peaks: "Mount Elbert (14,433')",
    highest_peak_elevation: 14433,
    peak_count: 1
  },
  {
    id: 4,
    number: 4,
    name: "GUARDIANS OF THE FLATIRONS",
    description: "This three-peak traverse is the pride of Boulder, giving you a deluxe tour of the local mountains and the slanted pinnacles of the Flatirons. It's a big hike that's right in town.",
    round_trip_miles: 12.1,
    hiking_time_min: 7,
    hiking_time_max: 10,
    difficulty_rating: 6.5,
    difficulty_label: "6.5/10",
    class_numeric: 2,
    class_text: "2",
    start_elevation: 5833,
    total_elevation_gain: 5171,
    terrain: "On-trail tour of Boulder's Flatirons",
    crowd_level_numeric: 4,
    crowd_level_text: "Moderate overall; high on Green Mountain and the Mesa Trail",
    is_overnight: false,
    gear_advisor: "Normal gear",
    all_peaks: "Green Mountain (8,144'), Bear Peak (8,461'), South Boulder Peak (8,549')",
    highest_peak_elevation: 8549,
    peak_count: 3
  }
];